### PR TITLE
Hotfix zh_cn.json

### PR DESCRIPTION
**Pull request by ChuijkYahus**

### CODE REVIEW

**Comment by TwistedGate** [comment]
Darn, if i had known this PR would happen i would've waited a bit before the 16 release :c

**Comment by ChuijkYahus** [comment]
Terribly sorry about the late post.
*actually i only noticed en_us getting an update after version 16 got released*

**Comment by TwistedGate** [comment]
> Terribly sorry about the late post. _actually i only noticed en_us getting an update after version 16 got released_

Oh.. 😅

**Comment by TwistedGate** [comment]
Is this ready for merging?

**Comment by ChuijkYahus** [comment]
> Is this ready for merging?

Yeah, it's all done.

**Pull request merged**
