### PR TITLE
update to 1.19.2

### PR DESCRIPTION
**Pull request by coco875**
It compile but the game don't run

### CODE REVIEW

**Comment by coco875** [comment]
ok now the game launch

**Comment by coco875** [comment]
if you want to try the updated version of the mod
https://github.com/coco875/ImmersivePetroleum/actions/runs/6131561047

**Comment by furtabs** [comment]
I appreciate this PR, but find it sad the dev probably won't merge it and do the port themselves. Thoughts @TwistedGate

**Comment by coco875** [comment]
> I appreciate this PR, but find it sad the dev probably won't merge it and do the port themselves. Thoughts @TwistedGate

I hope he will merge or if he want to change something, he make a rewiew

**Comment by TwistedGate** [comment]
> I appreciate this PR, but find it sad the dev probably won't merge it and do the port themselves. Thoughts @TwistedGate

My plan was always to port it, only a few days ago have i found enough motivation and will power to actualy do it.
And since i havent checked github in a very, very long time and only have seen the PR *after* i've made my port public (default checking if everything got uploaded correctly) im now in a weird position with having basicly 2 `1.19.2` ports..

Which also means i have to check all those 100+ files, check the differences and decide what to keep and what to toss from this <_<

**Comment by coco875** [comment]
see https://github.com/TwistedGate/ImmersivePetroleum/pull/165 for the continuity

**Pull request closed without merging**
